### ISSUE TITLE
crosstool_wrapper_driver_is_not_gcc

### ISSUE THREAD

**Issue by TrevorDecker** [kgreenek/rules_pcl#6]
When I attempt to build with the following rule:

```
twa_cc_binary(
    name = "calibration_icp",
    srcs = [
        "calibration_icp.cpp",
    ],
    deps = [
        "@pcl//:common"
    ],
)
```

I get the following error:
```ERROR: /home/trevor/thirdwave/twa/slam/BUILD.bazel:289:14: C++ compilation of rule '//twa/slam:calibration_icp' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/twa/slam/_objs/calibration_icp/calibration_icp.d ... (remaining 374 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/twa/slam/_objs/calibration_icp/calibration_icp.d ... (remaining 374 argument(s) skipped)```

**Comment by kgreenek** [comment]
Sorry for the delay in responding to this. Thank you for filing this issue.

I will need a bit more information to help, I'm afraid. If you are still seeing this bug, it would be helpful to create a minimal example to reproduce that I would be able to run. It looks like you have a toolchain with cuda / cross-compiling. That's about all I can tell from the error message. The actual error appears to be omitted.

**Comment by kgreenek** [comment]
I'm going to close this for now since I don't have any way to reproduce and it is getting stale. But please re-open if it is still an issue for you and can help me with some more details.
